//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kangur.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hero_snapshotKeyText {
            get {
                return ((string)(this["hero_snapshotKeyText"]));
            }
            set {
                this["hero_snapshotKeyText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int hero_snapshotKeyCode {
            get {
                return ((int)(this["hero_snapshotKeyCode"]));
            }
            set {
                this["hero_snapshotKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hero_loadKeyText {
            get {
                return ((string)(this["hero_loadKeyText"]));
            }
            set {
                this["hero_loadKeyText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int hero_loadKeyCode {
            get {
                return ((int)(this["hero_loadKeyCode"]));
            }
            set {
                this["hero_loadKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hero_boostKeyText {
            get {
                return ((string)(this["hero_boostKeyText"]));
            }
            set {
                this["hero_boostKeyText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int hero_boostKeyCode {
            get {
                return ((int)(this["hero_boostKeyCode"]));
            }
            set {
                this["hero_boostKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string environment_loadLevelText {
            get {
                return ((string)(this["environment_loadLevelText"]));
            }
            set {
                this["environment_loadLevelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int environment_loadLevelKeyCode {
            get {
                return ((int)(this["environment_loadLevelKeyCode"]));
            }
            set {
                this["environment_loadLevelKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_0_best {
            get {
                return ((long)(this["ilstimer_0_best"]));
            }
            set {
                this["ilstimer_0_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_1_best {
            get {
                return ((long)(this["ilstimer_1_best"]));
            }
            set {
                this["ilstimer_1_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_2_best {
            get {
                return ((long)(this["ilstimer_2_best"]));
            }
            set {
                this["ilstimer_2_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_3_best {
            get {
                return ((long)(this["ilstimer_3_best"]));
            }
            set {
                this["ilstimer_3_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_4_best {
            get {
                return ((long)(this["ilstimer_4_best"]));
            }
            set {
                this["ilstimer_4_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_5_best {
            get {
                return ((long)(this["ilstimer_5_best"]));
            }
            set {
                this["ilstimer_5_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_6_best {
            get {
                return ((long)(this["ilstimer_6_best"]));
            }
            set {
                this["ilstimer_6_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_7_best {
            get {
                return ((long)(this["ilstimer_7_best"]));
            }
            set {
                this["ilstimer_7_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_8_best {
            get {
                return ((long)(this["ilstimer_8_best"]));
            }
            set {
                this["ilstimer_8_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_9_best {
            get {
                return ((long)(this["ilstimer_9_best"]));
            }
            set {
                this["ilstimer_9_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_10_best {
            get {
                return ((long)(this["ilstimer_10_best"]));
            }
            set {
                this["ilstimer_10_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_11_best {
            get {
                return ((long)(this["ilstimer_11_best"]));
            }
            set {
                this["ilstimer_11_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_12_best {
            get {
                return ((long)(this["ilstimer_12_best"]));
            }
            set {
                this["ilstimer_12_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_13_best {
            get {
                return ((long)(this["ilstimer_13_best"]));
            }
            set {
                this["ilstimer_13_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_14_best {
            get {
                return ((long)(this["ilstimer_14_best"]));
            }
            set {
                this["ilstimer_14_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_15_best {
            get {
                return ((long)(this["ilstimer_15_best"]));
            }
            set {
                this["ilstimer_15_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_16_best {
            get {
                return ((long)(this["ilstimer_16_best"]));
            }
            set {
                this["ilstimer_16_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_17_best {
            get {
                return ((long)(this["ilstimer_17_best"]));
            }
            set {
                this["ilstimer_17_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_18_best {
            get {
                return ((long)(this["ilstimer_18_best"]));
            }
            set {
                this["ilstimer_18_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_19_best {
            get {
                return ((long)(this["ilstimer_19_best"]));
            }
            set {
                this["ilstimer_19_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_20_best {
            get {
                return ((long)(this["ilstimer_20_best"]));
            }
            set {
                this["ilstimer_20_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_21_best {
            get {
                return ((long)(this["ilstimer_21_best"]));
            }
            set {
                this["ilstimer_21_best"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_0_backup {
            get {
                return ((long)(this["ilstimer_0_backup"]));
            }
            set {
                this["ilstimer_0_backup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_clean {
            get {
                return ((long)(this["ilstimer_clean"]));
            }
            set {
                this["ilstimer_clean"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_1_backup {
            get {
                return ((long)(this["ilstimer_1_backup"]));
            }
            set {
                this["ilstimer_1_backup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ilstimer_2_backup {
            get {
                return ((long)(this["ilstimer_2_backup"]));
            }
            set {
                this["ilstimer_2_backup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string environment_forceLoadAllTexturesText {
            get {
                return ((string)(this["environment_forceLoadAllTexturesText"]));
            }
            set {
                this["environment_forceLoadAllTexturesText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int environment_forceLoadAllTexturesKeyCode {
            get {
                return ((int)(this["environment_forceLoadAllTexturesKeyCode"]));
            }
            set {
                this["environment_forceLoadAllTexturesKeyCode"] = value;
            }
        }
    }
}
